---
# tasks file for jenkins
- name: add jenkins key
  apt_key:
    state: present
    url: "{{ jenkins_key_rpm }}"

- name: "Set EPEL apt repository"
  apt_repository:
    filename: "{{ item.value.name }}"
    repo: "{{ item.value.url }}"
  loop:
    "{{ lookup('dict',repos, wantlist=True) }}"    

- name: "Install Java and Jenkins"
  apt:
      name: "{{ item.value.name }}" 
      state: present
  loop:
    "{{ lookup('dict',softwares) }}"

- name: "Starting jenkins"
  service:
      name: "jenkins"
      state: started
      enabled: yes